monitor.bluez.rules = [
  {
    matches = [
      {
        device.name = "~bluez_output.*"
      }
    ]
    actions = {
      update-props = {
        # Increase quantum for bluetooth to avoid underruns
        clock.min-quantum = 512
      }
    }
  }
]
